# Generated by Django 4.2.7 on 2023-12-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_answer_next_question_alter_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
    ]
